# Generated by Django 3.0.6 on 2020-05-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200524_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent_id',
        ),
    ]
